### ISSUE TITLE
HTML/CSS: Events Public Page

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#1]
Produce HTML/CSS files for this page using the attached design.
We may perform the Wordpress/PHP integration ourselves.
[Events Public Page_FA.zip](https://github.com/cmmadmin/srs/files/987508/Events.Public.Page_FA.zip)

**Comment by cmmadmin** [comment]
I have provided 
[Font Details.pdf](https://github.com/cmmadmin/srs/files/987585/Font.Details.pdf)
a PDF reference guide that gives the font sizes and weights for each of the different type elements that will be on each page. The PDF file name is called "FontDetails.PDF"

**Comment by clns** [comment]
https://clns.github.io/srs/events.html

![events](https://cloud.githubusercontent.com/assets/687922/26070745/696e410c-39ae-11e7-8a2a-c931d1c2c449.png)

Mobile:

![events-iphone](https://cloud.githubusercontent.com/assets/687922/26070754/6e66be78-39ae-11e7-80f4-f42625e7870d.png)
