### ISSUE TITLE
HTML/CSS for Support Raising Leader’s Conference 2018 page

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#12]
Produce HTML/CSS files for this page using the design [here](https://drive.google.com/open?id=0B_5uyZ9qoMMWRlBXRGNqVG03N0E).

We need this completed by beginning of the day 7/17/2017 or earlier. If it could be done by 7/14/2017 that would be better.

We plan to paste the HTML into the content portion of this post:
https://supportraisingsolutions.org/conference/support-raising-leaders-conference-2018/
https://supportraisingsolutions.org/wp-admin/post.php?post=3802&action=edit

We plan to add the CSS to the style.css file.

NOTE: The post currently contains the content from this previous conference:
https://supportraisingsolutions.org/conference/support-raising-leaders-conference-2016/

Rationale: The post is a Conference custom post type. Each conference we host tends to have a unique style for the pages, so we tend to to use a top-level selector (e.g., "#climb") to partition the style from the rest of the site.

We are ok with you just producing the HTML/CSS, but if you have a better idea for the Wordpress integration we can consider that as well.

I will refresh the database and content at staging.supportraisingsolutions.org so you can work with the latest there if necessary. I will do that shortly. All latest code is in Github (we have made several changes since your last work).

**Comment by cmmadmin** [comment]
I have refreshed the staging.supportraisingsolutions.org site with files and database from the live site.

You can access the conference post where we will copy the html content here:
http://staging.supportraisingsolutions.org/conference/support-raising-leaders-conference-2018/
http://staging.supportraisingsolutions.org/wp-admin/post.php?post=3802&action=edit

Use can use this post from development and testing.

**Comment by danseciu** [comment]
Hi Malachi,

I've got a couple of questions about the design:

1. In the PSD the width of the page is 1900px. Is this the actual width that the HTML page should have ? or should it be 960px wide like the rest of the pages ?
2. We'll need the `Ocean Sans Std` font as a webfont so we can include it in CSS. There are about 7 styles of this font used in the design.

**Comment by cmmadmin** [comment]
1. The width should be 960px like the rest of the pages.
2. We have included the Ocean Sans project using the fast fonts project as in functions.php as follows:

```
function my_add_styles() {
    ...
    wp_enqueue_style('fastfonts', 'https://fast.fonts.net/cssapi/f357d5b8-ac37-447c-87e5-1e7316edbd58.css');
}
```

The fonts in this project are shown in the attached screenshots.

**Comment by danseciu** [comment]
I've tried logging in on staging with user `calin@softped.com` but it says the username doesn't exist. Also tried the forgot password link but same error.

Can you also update the database snapshot (uscwmmob_srsstaging.sql) on staging ?

**Comment by cmmadmin** [comment]
I have updated the sql file here: /public_html/supportraisingsolutionsStaging/uscwmmob_srsstaging.sql

I also created an account for you on the staging site with:
u: calin@softped.com
I will email you the password.

**Comment by danseciu** [comment]
I've created a pull request with the CSS changes for this.

The HTML and the images can be downloaded here:
https://drive.google.com/drive/folders/0By84t7eAWAEubGVMRFhYMHlWRlk?usp=sharing

The images can be uploaded from admin or added to `/wp-content/uploads/2017/07/`

**Comment by cmmadmin** [comment]
danseciu, I've deployed the Full Sail page. The names of the speakers are overlapping with their images in the Speakers section. What do you recommend as a fix for this?

You can view the live page here:
https://supportraisingsolutions.org/conference/support-raising-leaders-conference-2018/

**Comment by danseciu** [comment]
There is an SVG path at the beginning of `<section class-"speakers">` that gets filtered out when saving the post in admin.

In order to fix this it needs to be added in just one line:

```html
<svg width="0" height="0"><defs><clipPath id="speaker-image-clip"><path d="M188,0V106s5,81.75-94,112C-5,188,0,106,0,106V0Z"/></clipPath></defs></svg>
```

**Comment by cmmadmin** [comment]
danseciu, The SVG path that you provided was already in the html code (see attached). I re-added it, but still not fixed. I deployed your code to the staging site so you can test it there. Any ideas? I recall we had this same problem on another page you delivered. I believed I added a fixed height on that page. But inthis case a fixed height and width distorts the images.

http://staging.supportraisingsolutions.org/conference/support-raising-leaders-conference-2018/
http://staging.supportraisingsolutions.org/wp-admin/post.php?post=3802&action=edit
![2017-07-16](https://user-images.githubusercontent.com/6864440/28250537-ad349ffa-6a30-11e7-8d5f-f2f260abb260.png)

**Comment by danseciu** [comment]
I've went in admin on staging and replaced the old SVG code with that one line. No other changes should be required.

**Comment by cmmadmin** [comment]
Ok, looks good now. Thanks. Must need to be all on one line to work.
