### ISSUE TITLE
Speaker photos on Safari, MS Edge, IE, and Chrome iOS

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#14]
The styling on the speaker photos on this page is not working on Safari, MS Edge, Internet Explorer, and Chrome iOS. 
https://supportraisingsolutions.org/conference/support-raising-leaders-conference-2018/

Can you implement a fix to support these browsers? Or, should we resort to using transparent PNGs?

We need to have this fixed by Sep 1 because we are sending a big mailing next week.

**Comment by cmmadmin** [comment]
![2017-08-30](https://user-images.githubusercontent.com/6864440/29897009-b20feae2-8da4-11e7-8405-b678fe446572.png)

**Comment by cmmadmin** [comment]
![2017-08-30 1](https://user-images.githubusercontent.com/6864440/29897036-ce816e44-8da4-11e7-8452-df476b795f7a.png)

**Comment by cmmadmin** [comment]
We implemented a work around on our live site. We baked the shield effect into the images. So the deadline on this is no longer urgent.

You can still see the old version with the issue on our staging site here:
https://staging.supportraisingsolutions.org/conference/support-raising-leaders-conference-2018/

Let us know if you have a quick cross-platform solution that does not require the workaround. But don’t spend much time on this.

**Comment by danseciu** [comment]
There isn't one cross-platform solution for this, we can use a different approach and use a CSS "mask",  which should work on most browsers, except Edge/IE - however it will not overlap the text with the image anymore, it will look like this on Edge/IE:
![image](https://user-images.githubusercontent.com/2210838/29963307-f9804c76-8f0e-11e7-9e25-7f408d9965e8.png)

Let me know if we should implement this solution on staging (I can't login to staging anymore with user calin@softped.com)

**Comment by cmmadmin** [comment]
Thanks. We are going to stick with the baked images workaround for now.
