### ISSUE TITLE
Network Page HTML/CSS and Wordpress Integration

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#15]
We need to replace the page at supportraisingsolutions.org/network with the new design (see Network Page.psd).

A new page at supportraisingsolutions.org/training will also be added which will be linked from the Network page. Design for this page will be coming soon.

We need this complete by Sep 20 for a conference.

**Comment by cmmadmin** [comment]
The design for the Network page (supportraisingsolutions.org/network) is here:

http://staging.supportraisingsolutions.org/2107-09-Network-Page.zip

**Comment by danseciu** [comment]
Hey Malachi,

I won't be able to work on these changes as I'm travelling all next week, but we might have someone else do the work.
I've tried to get the design files but can't no longer connect through FTP to the staging server using the softped@everyethne.org account.

**Comment by cmmadmin** [comment]
Dan, 

You should be able to download the designs using this link: http://staging.supportraisingsolutions.org/2107-09-Network-Page.zip

I will restore your FTP access as well.

Please let me know if your developer is available. We will need to make other arrangements if he is not.

-Malachi

**Comment by cmmadmin** [comment]
I reset the password for the softped@everyethne.org FTP account to the same one as your Wordpress account on the staging site. Let me know if you are still unable to connect.

**Comment by cmmadmin** [comment]
We should have the PSD for the Training page within a couple of hours as well.

**Comment by cmmadmin** [comment]
Attached is a JPG of the design for the Training page. I will have the PSD version within the hour but hopefully this gives you a good idea.
![training-page-2](https://user-images.githubusercontent.com/6864440/30494477-dd38b3dc-9a0d-11e7-8703-d4a9aef7e09c.jpg)

**Comment by cmmadmin** [comment]
I have replaced the design files in the site root with PSDs for both the Network (supportraisingsolutions.org/network) and Training (supportraisingsolutions.org/training) pages. We optimized the files so they are much smaller. They are in the site root here:

http://staging.supportraisingsolutions.org/TrainingPage2_WebDev.psd
and
http://staging.supportraisingsolutions.org/NetworkPage2_WebDev.psd

**Comment by danseciu** [comment]
Alright, we have reviewed the designs and Ovi (@ovidiudinu) will be able to do the work. I'll make sure he has access to the staging files and database.

Also can you please add him to this repository ?

**Comment by cmmadmin** [comment]
I have added https://github.com/ovidiudinu as collaborator to the https://github.com/cmmadmin/srs repository.

**Comment by ovidiudinu** [comment]
Yes....I will let you know after I commit the changes.

**Comment by ovidiudinu** [comment]
I have a little issue here. What do you mean by commit them into master/trunk? I don't know exactly what master/trunk is.

**Comment by cmmadmin** [comment]
Nevermind. Let's go with your original idea of creating a folder in the root of the repository and upload all the files there.

**Comment by ovidiudinu** [comment]
I tried to push my changes but I get a 403 error. I think I don't have access to push.

**Comment by cmmadmin** [comment]
It looks like you haven't accepted the invitation to become a collaborator on this repository. Try to accept it using this link: https://github.com/cmmadmin/srs/invitations or check your email for the invitation.

**Comment by ovidiudinu** [comment]
OK...I pushed all the files into 2017-09-18 folder. Inside you have the same structure as where they should go.

**Comment by cmmadmin** [comment]
Thank you. We will check them out.

**Comment by cmmadmin** [comment]
Thank you. The pages look great. We published them to our live site: https://supportraisingsolutions.org/network
