### ISSUE TITLE
Mobile Responsive Page Template for Conference Audio Page

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#17]
Can you implement a page template that we can add to our Wordpress theme that we can use to make the following page mobile responsive?

http://staging.supportraisingsolutions.org/leaders-conference-2016/

We need this completed by Jan 31. Can someone on your team help us with this by then?

We need to move towards making this site mobile responsive. This may serve as a logical first step in that direction. We would also love to hear your thoughts about how hard it would be to make the entire site mobile responsive.

**Comment by clns** [comment]
Can you give us the login to access that page please?

**Comment by cmmadmin** [comment]
Wordpress login:
http://staging.supportraisingsolutions.org/wp-admin
calin@softped.com
I have sent the password by email to Calin.

**Comment by ovidiudinu** [comment]
We tried with calin@softped.com and the password you sent to him but it's not working.

**Comment by cmmadmin** [comment]
Hmmm. I just tried it in Chrome and Firefox and I was able to login.

Are you using the password that ends with: T#ST
I send that password to Calin 3 minutes ago.

**Comment by clns** [comment]
It worked. I didn't see the second password. Thanks. We'll update the issue soon.

**Comment by cmmadmin** [comment]
Hello. Have you had a chance to look at this? Do you think this page can be made mobile responsive by January 31?

**Comment by clns** [comment]
We looked at the page, and I think there are 2 concerns:

1. How will the header and menu look like? I think these two will have to be made responsive for all the pages, since they most likely render on all pages.
2. I see the audio player loads a swf file. This won't work on mobile devices, so I think we need to replace that audio player with something else, ideally native.

**Comment by cmmadmin** [comment]
RE #1:

Making the header and menu responsive on all pages is fine. 

If making the header responsive on all pages causes many issues on other pages, then could we create a copy of header.php and make that version of the header responsive and then load it only on this page (by passing it to get_header(...) in the page template? 

A good template to start with may be page-FullWidth.php

I suspect you will need to setup the viewport. header.php currently contains the following:

if ( $udesign_options['enable_responsive'] ) echo '<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />'; ?>

The udesign them has some support for responsiveness but I don't believe it has worked well probably because we have made so many modifications to the theme.

RE #2:

Don't worry about the swf audio player. We will fix that.

**Comment by cmmadmin** [comment]
As a test, I created a page template called "page-FullWidthNoHeader.php" and a new header called "header-responsive.php" which is loaded with:

`get_header( "responsive" );`

I stripped out the header and a lot of other content from header-responsive.php just for my test.

These files on the staging site.

Could you create a better version of these two files (header-responsive.php and page-FullWidthNoHeader.php) that includes the header and menu, and all of the other necessary things from header.php that I stripped out?

**Comment by clns** [comment]
I think yes, thanks. We'll work on it starting today and through the weekend.

**Comment by ovidiudinu** [comment]
Could you please make a new DB dump and upload it to the FTP root?

**Comment by cmmadmin** [comment]
On Jan 19 I placed an sql file in the site root of the staging site with a
dump of the database. Do you see it?

**Comment by ovidiudinu** [comment]
Yes...I found it. Thank you.

**Comment by ovidiudinu** [comment]
I commited this [ZIP file](https://github.com/cmmadmin/srs/blob/master/update-20180128091100.zip) in this repository containing all the changes required for the responsive layout.
When testing use the FullWidthResponsive page layout.

**Comment by cmmadmin** [comment]
Thank you this looks good. I have integrated it. We will let you know if we encounter any issues. So far it is looking good.
