### ISSUE TITLE
HTML/CSS: Network Home Page

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#2]
Produce HTML/CSS files for this page using the attached design.
Produce code for the blue menu.
[Network Home Page_FA.zip](https://github.com/cmmadmin/srs/files/987522/Network.Home.Page_FA.zip)

We may perform the Wordpress/PHP integration ourselves.

**Comment by clns** [comment]
https://clns.github.io/srs/index.html

![network-home](https://cloud.githubusercontent.com/assets/687922/26070706/3cdc7e88-39ae-11e7-9a5b-a469309b347b.png)

Mobile:

![network-home-iphone](https://cloud.githubusercontent.com/assets/687922/26070713/42ae47ec-39ae-11e7-8ad0-aad05984fc6e.png)
