### ISSUE TITLE
HTML/CSS: Network Member News

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#3]
Produce HTML/CSS files for this page using the attached design.
We may perform the Wordpress/PHP integration ourselves.
[Network Member News Page_FA.zip](https://github.com/cmmadmin/srs/files/987526/Network.Member.News.Page_FA.zip)

**Comment by clns** [comment]
https://clns.github.io/srs/network-news.html

![network-news](https://cloud.githubusercontent.com/assets/687922/26070778/854499a8-39ae-11e7-8059-58c84f028f6c.png)

Mobile:

![network-news-iphone](https://cloud.githubusercontent.com/assets/687922/26070783/89de4a86-39ae-11e7-8394-1a5f344d55c6.png)
