### ISSUE TITLE
HTML/CSS: SRS Global Team

### ISSUE THREAD

**Issue by cmmadmin** [cmmadmin/srs#4]
Produce HTML/CSS files for this page using the attached design.
We may perform the Wordpress/PHP integration ourselves.
[SRS Global Team_FA.zip](https://github.com/cmmadmin/srs/files/987531/SRS.Global.Team_FA.zip)

**Comment by clns** [comment]
https://clns.github.io/srs/global-team.html

![global-team](https://cloud.githubusercontent.com/assets/687922/26070799/975720a2-39ae-11e7-8f52-4f7af48eacaa.png)

Mobile:

![global-team-iphone](https://cloud.githubusercontent.com/assets/687922/26070805/9c6ee46c-39ae-11e7-88ac-607287d1c3b9.png)
